openapi: 3.0.1
info:
  title: api
  version: ''
paths:
  /movies/{movieId}:
    get:
      operationId: imdb_getMovie
      tags:
        - Imdb
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/MovieId'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      error:
                        type: string
                        enum:
                          - MovieDoesNotExistError
                      content:
                        $ref: '#/components/schemas/MovieId'
components:
  schemas:
    MovieId:
      title: MovieId
      type: string
    Movie:
      title: Movie
      type: object
      properties:
        id:
          $ref: '#/components/schemas/MovieId'
        title:
          type: string
        rating:
          type: number
          format: double
          description: The rating scale is one to five stars
      required:
        - id
        - title
        - rating
    OuterUnion:
      title: OuterUnion
      oneOf:
        - type: object
          allOf:
            - type: object
              properties:
                type:
                  type: string
                  enum:
                    - child
            - $ref: '#/components/schemas/InnerUnion'
    InnerUnion:
      title: InnerUnion
      type: object
      properties:
        field_a:
          type: string
        field_b:
          type: integer
  securitySchemes: {}
