name: "Backend"

on:
  pull_request:
  push:
    branches: [master]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Install fern
        run: npm install -g fern-api
      - name: fern generate
        run: fern generate
        env:
          FERN_TOKEN: dummy
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: mypy
        run: poetry run mypy