name: "Fern Check"

on:
  pull_request:
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Install fern
        run: npm install -g fern-api
      - name: fern generate
        run: fern generate
      - name: Install dependencies
        run: poetry install
      - name: mypy
        run: poetry run mypy