name: "Fern Check"

on:
  pull_request:
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install fern
        run: npm install -g fern-api
      - name: fern check
        run: fern check